from .SolutionGenerator import *

class SolutionMapping:
    ##missing 8,13,20-23,25,37,40,63,74-76
    def __init__(self):
        self.__solution_classes = {
            1: KnowledgePoint1Solution,
            2: KnowledgePoint2Solution,
            3: KnowledgePoint3Solution,
            4: KnowledgePoint4Solution,
            5: KnowledgePoint5Solution,
            6: KnowledgePoint6Solution,
            7: KnowledgePoint7Solution,
            9: KnowledgePoint9Solution,
            10: KnowledgePoint10Solution,
            11: KnowledgePoint11Solution,
            12: KnowledgePoint12Solution,
            14: KnowledgePoint14Solution,
            15: KnowledgePoint15Solution,
            16: KnowledgePoint16Solution,
            17: KnowledgePoint17Solution,
            18: KnowledgePoint18Solution,
            19: KnowledgePoint19Solution,
            24: KnowledgePoint24Solution,
            26: KnowledgePoint26Solution,
            27: KnowledgePoint27Solution,
            28: KnowledgePoint28Solution,
            29: KnowledgePoint29Solution,
            30: KnowledgePoint30Solution,
            31: KnowledgePoint31Solution,
            32: KnowledgePoint32Solution,
            33: KnowledgePoint33Solution,
            34: KnowledgePoint34Solution,
            35: KnowledgePoint35Solution,
            36: KnowledgePoint36Solution,
            38: KnowledgePoint38Solution,
            39: KnowledgePoint39Solution,
            41: KnowledgePoint41Solution,
            42: KnowledgePoint42Solution,
            43: KnowledgePoint43Solution,
            44: KnowledgePoint44Solution,
            45: KnowledgePoint45Solution,
            46: KnowledgePoint46Solution,
            47: KnowledgePoint47Solution,
            48: KnowledgePoint48Solution,
            49: KnowledgePoint49Solution,
            50: KnowledgePoint50Solution,
            51: KnowledgePoint51Solution,
            52: KnowledgePoint52Solution,
            53: KnowledgePoint53Solution,
            54: KnowledgePoint54Solution,
            55: KnowledgePoint55Solution,
            56: KnowledgePoint56Solution,
            57: KnowledgePoint57Solution,
            58: KnowledgePoint58Solution,
            59: KnowledgePoint59Solution,
            60: KnowledgePoint60Solution,
            61: KnowledgePoint61Solution,
            62: KnowledgePoint62Solution,
            64: KnowledgePoint64Solution,
            65: KnowledgePoint65Solution,
            66: KnowledgePoint66Solution,
            67: KnowledgePoint67Solution,
            68: KnowledgePoint68Solution,
            69: KnowledgePoint69Solution,
            70: KnowledgePoint70Solution,
            71: KnowledgePoint71Solution,
            72: KnowledgePoint72Solution,
            73: KnowledgePoint73Solution,

        }
    def getKnowledgePoint(self, id):
        if id not in self.__solution_classes:
            return None
        return self.__solution_classes.get(id)